#' run
#' 
#' Last modified: 2018-05-03
#'
setwd("/var/www/html/fold");
Sys.setlocale("LC_ALL", 'en_GB.UTF-8');
# Packages and functions -------------------------------------------------------
library(ggplot2);
library(dplyr);
library(stringr);
# library(readr);
source("fn/fold.R");
source("fn/fold_multi.R");
source("fn/make_linker.R");
source("fn/sq_comp.R");
source("fn/sq_match.R");
source("fn/str2chr.R");
source("fn/plot_rcp.R");
source("fn/compare_fix.R");
source("fn/compare_check.R");

# Test input (for debugging) ---------------------------------------------------
 
#sq1 <- casefold(str2chr(str_remove_all("NNNNNNNNNNNNGGCGATTGATTTAGCGGCCGCGAATTCGCCCTTTATTAGGGAGTGTTAGATAGTGGGCGTAGGTTAGTGTGTGTGCGTATCGTGCGCGAGTCGAAGTAGGGCGAGGTATTGTTTTATTTGGGAAGCGTAAGGGGTTAGGGAGTTTTTTTTCCGAGTCAAAGAAAGGGGTGACGGACGTATTTGGAAAATCGGGTTATTTTTATTCGAATATTGCGTTTTTTAGATCGGTTTAAATTGTGTAAATTTGATTGtATGATTTAAGTCGGTTTGAAAAGCGTAATATTCGGGTGGGAGTGATTCGATTTTTTAGGTGCGTCCGTCATCCTTTTCTTTGACTCGGAAAGGGAATTTTTTGATTTTTTGCGTTTTTTAGGTGAGGTAATGTTTCGTTTTGTTTCGGTTTGCGTACGGTGCGTATATATATTGGTTTGTGTTTATTGTTTGGAAGGGCGAATTCGTTTAAACCTGNATGACTAGTCCCTTTAGTGAGGGTCAATTCTGAGCTTGNCNTAATCATGGTCATNNCTGTTTCCTGTGTGAANNNNTTATCCGCTCNCANTTCCACACNNNNNANGNNNNNNAANCATANNNTGTNNANCNTTGNNNTGCCTANTGAGTGACCTAACTCANNNNNTNTGNNNNGNNC", "[\n\r ]")), upper=TRUE);
#sqs <- list(sq1);
#sqs <- "NNNNNNNNNNNNNNNNNNNNGGANGTANNNNCCATGATTATCGCAAATCAAAACAAAACAAACTCAACAAAATACACGATAAAAAAAAAAACAAAAACAAACCAACAAAAAAAAATATATAAAAAAACAACCAAAAAACAAAAAAAAAAATACAATCCACACTCAAAAACCATCCAAAACATTACACATATCTTCAAACATATAATATCTTAAACAACCTCTAAATACAAACCACACCCCTCTCCCCACCCCTTAACTACCCTTCCACACACCCTTCCCTACCAACCCACCCCTACCCTCCCCCTCTTACCGCACACCCCGCTAAATCTACTCTACCTTAACCTACAACAATACCCAATAACCCAATAACCTCCTTCCTACTACTGATAATAATTAATTAAGACGTCAGAATTCTCGAGGCGGCCGCATGTGCGTCTCCCTATAGTGAGTCGTATTAATTTCGCGGGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGGAGGACCGAAAGGAGCTAACCGCTTTTTTTGCACAACATGGGGGGATCATGGTAACTCGGCCTTGATCGNTGGGGAACCGGANGCTGANTTGAAGCCCATACCAANCNNNCGAACNNNGACACCNCCGATGCNNGGTAGNCATGGNNAACCAACGGTTGCCGCAAANCTATTNAACTGGGCGAANCTACTTNACTCTAGNCTTNCCCGGGCAACAATTNAANNAAANCTGGGATGGGAGGNGGNAATAAANGTTGGCAAGGAACCNCTTNCTGGNNNNNCCGGGCCNTTNCCNGGGCTGGGNNTGGNTTNNTTGGCTTNANNAANTNNNGGNANNCCCGGNNNANNCGGGGGNATTCTCCNNNGGNNNNNNATTTGGNNNNNCCNTTGGGGGGNCCNAANANNGGNAAANNCCNNNNCCNNNGTNNNNNNNAANNTTNNNNNNNNNNCCNNAACCGGGGGNAANNNNNNNGGNNNAANNNNANGGNNNNNNAANNNNNAAANNNNNAANNNCNNNNANTTNNNTNNNAANNNNNAAGGGNNNNNNNNNNCCNANNGGAATTTNAAANCNNNNTTNNNNNNNNAANCNTGGGNNNNNNANNCCNNAANNNNTTTTNANNNNNCNNTNNANNNNAAANNCCNTTTTNNNAANNNNNNNNNNTTTTTNAANAAANNNNNNNNNNNNNNNTTTTTNNNAANNTTNTNNNNAAAAANGNNNNNTTNNNNNNNGGGGNTNNAANNNANNNNNNNNNTTTTNNTTTNNNANNNAANNTTNNNNNNNNNNNGNNNNNNNNAAAAAANTTNCCCCNNNNTTNNAAANCNTNGNNNNNNNNNNTTTTNNNNNNNT,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGAGGAGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTATGGGAGAATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTTGTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTTGTATTTAGAGGTTGTTTAAGATATTATATGTGATTGTAAATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,CGGGGTGTGCGGTAAGAGGGGGAGGGCAGGGGCGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTATAGGGAAATGTGTAACGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATCGTGTATTTCG,CGGGGTGTGCGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTTTGAAGATATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATCGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTTGTATTTAGAGGTTGTTTAAGATATTATATGTTGGTTAAAATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGGGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTTAAAGAAAATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGTTTGTATTTGGAGGTTGTTTAAGATATTATATGTTATTTTTTATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGCAGTTAAGGGGTGGGGAGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTTGTATGTAATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTTGTATTTAGAGGTTGTTTAAGATGTTATATGTAAGTAAAGATGTGTAATGTTTTGGATGGTTTTTGAGTGCGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTCTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,CGGGGTGTGCGGTAAGAGGAGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTCGTATTTAGAGGTCGTTTAAGATATTATATGTAAAATTGAATGTGTAATGTTTTGGACGGTTTTTGAGTGCGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATCGTGCATTTTG,TGGGGTGTGTGGTGAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTTGTATTTAGAGGTTGTTTAAGATATTATATGTGTGTGGGGATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTCGTATTTAGAGGTTGTTTAAGATATTATATGTTAGTTGGAATGTGTAATGTTTTGGATGGTTTTTGAGTGCGGTTTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,CGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGTTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGCGGGGAGAGGGGTGCGGGTCGTATTTAGAGGTCGTTTAAGATATTATATGTAATGTAAAATGTGTAATGTTTTGGACGGTTTTTGAGTGCGGTTCGTATTTTTTTTTTCGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTCGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTCG,TGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGTTTGTATTTAGAGGTTGTTTAAGATATTATATGTTTGGTAGGATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGATTGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTTG,CGGGGTGTGCGGTAAGAGGGGGAGGGTAGGGGTGGGTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGTGGGGAGAGGGGTGTGGGTTGTATTTAGAGGTTGTTTAAGATATTATATGTGTATTATGATGTGTAATGTTTTGGATGGTTTTTGAGTGTGGTTCGTATTTTTTTTTTTGTTTTTTGGTTGTTTTTTTATATATTTTTTTTGTTGGTTTGTTTTTGTTTTTTTTTTTTTTATTGTGTATTTCG,CGGGGTGTGTGGTAAGAGGGGGAGGGTAGGGGTGGTTTGGTAGGGAAGGGTGTGTGGAAGGGTAGTTAAGGGGCGGGGAGAGGGGTGCGGGTCGTATTTAGAGGTCGTTTAAGATATTATATGTAATGTAAAATGTGTAATGTTTTGGACGGTTTTTGAGTGCGGTTCGTATTTTTTTTTTCGTTTTTTGGTTGTTTTTTTATATATTTTTTTTTGTCGGTTTGTTTTTGTTTTTTTTTTTTTATTGTGTATTTCG
# ";
# 
#sqs <- lapply(
#  strsplit(sqs, split=",")[[1]], 
#  function(x){
#    return(casefold(str2chr(x), upper=TRUE))
#  }
#);
# 
#batch <- casefold(str2chr("GACATTACACGT"), upper=TRUE);
#barlen <- 8;
#side <- "right";
#sess <- "test";
#sqlen <- NA;

# Input ------------------------------------------------------------------------
args <- commandArgs(TRUE);
sqs <- lapply(strsplit(args[1], split=","), function(x){
  return(casefold(str_split(x, ""), upper=TRUE))
  });
batch <- casefold(str_split(args[2], ""), upper=TRUE);
barlen <- as.integer(args[3]);
side <- args[4];
sess <- args[5];
sqlen <- as.integer(args[6]);
source("temp.R");

# Run --------------------------------------------------------------------------
fld <- fold_multi(sqs, batch, barlen, side, sqlen);

# Make text output -------------------------------------------------------------
sink(paste0("txt/", sess, ".txt"));
cat(fld$summary);
sink();

# Make plot --------------------------------------------------------------------
plot <- plot_rcp(fld$U, fld$m, fld$rcp);
plot;
ggsave(
  filename=paste0("im/", sess, ".png"), 
  plot=plot, width=120, height=120, units="mm", dpi=300)

# ------------------------------------------------------------------------------
